### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by PandoricGalaxy** [0sir1ss/Anubis#1]
![image](https://user-images.githubusercontent.com/86944806/169659420-0ab1f649-e009-4088-922a-396987cd79f8.png)

**Comment by PandoricGalaxy** [comment]
any help?

**Comment by PandoricGalaxy** [comment]
@0sir1ss

**Comment by PandoricGalaxy** [comment]
Why closed it??? @0sir1ss

**Comment by 0sir1ss** [comment]
Fixed

**Comment by PandoricGalaxy** [comment]
![image](https://user-images.githubusercontent.com/86944806/169965080-84007356-396d-43dc-b344-e42edc601fb7.png)
Now new error

**Comment by 0sir1ss** [comment]
Try obfuscating without junk code or anti debugger and see what line the error is on

**Comment by PandoricGalaxy** [comment]
> Try obfuscating without junk code or anti debugger and see what line the error is on

Tried with all off but still...

**Comment by 0sir1ss** [comment]
Yes, the error is in the code your obfuscating. Check the line number and check the indentation. Make sure your code is compatible with python 3.3-3.7

**Comment by 0sir1ss** [comment]
Updated the obfuscator, code should now be compatible regardless of python 3.x.x version
