### ISSUE TITLE
Having trouble encoding

### ISSUE THREAD

**Issue by binhake** [0sir1ss/Anubis#11]
can you tell me what error this is?

![image](https://user-images.githubusercontent.com/60563332/188477374-a42a9ff7-68bb-44a0-989e-10881106266e.png)

**Comment by thien-nguyenthanh** [comment]
@binhake Did you resolve it? I am getting the same issue.

**Comment by binhake** [comment]
@thien-nguyenthanh I just tried reinstalling the script and it says "error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools /". I'm trying to find a workaround that I've tried successfully before.

**Comment by binhake** [comment]
@thien-nguyenthanh it seems that custom choices in the encoding you entered into the Script caused it to fail. I tried unchecking "Junk Code" and "Rename function,..." it worked!

**Comment by thien-nguyenthanh** [comment]
Thanks @binhake for your info.
Looks like Anubis is not support encode whole project so I am looking alternative tool.
