### ISSUE TITLE
PyInstaller instead of Nuitka?

### ISSUE THREAD

**Issue by xen-light** [0sir1ss/Anubis#25]
As the title states, why?

I tested Nuitka and PyInstaller and Nuitka was far worse in terms of speed than PyInstaller.

**Comment by YumYummity** [comment]
Speed in compiling, or speed when running?
Nuitka's output is arguably smaller, and compiles it into C.

While it is slower compiling, the output is harder to decompile and read, and is faster.

**Comment by xen-light** [comment]
I see.. thanks for the explanation!

**Comment by YumYummity** [comment]
np
