### ISSUE TITLE
lmao

### ISSUE THREAD

**Issue by 6nz** [0sir1ss/Anubis#7]
what is that lmao it would take 10 sec to deobfuscate it cuz u posted the decryptor 💀

**Comment by 6nz** [comment]
pointless

**Comment by 0sir1ss** [comment]
The decrypter is only for when you wish to distribute as a python file..

If you use the anti debugger and compile to an exe you will have a lot harder time trying to decompile it.

**Comment by 6nz** [comment]
> The decrypter is only for when you wish to distribute as a python file..
> 
> If you use the anti debugger and compile to an exe you will have a lot harder time trying to decompile it.

Anti debugger is useless u can just change the window name and its bypassed, also compiling doesnt secure the exe

**Comment by 0sir1ss** [comment]
Ok, well using the anti debugger forces the program to be ran as admin so assuming you use something like PH2 you won't be able to dump strings.

And Anubis uses Nuitka to compile the exe, not pyinstaller so tools like pyinstxtractor won't work to get the source back.

**Comment by 6nz** [comment]
Lol nuitka can be easily decompiled if u know C++

**Comment by 0sir1ss** [comment]
Ok, but you can decompile most things assuming you have knowledge of the language it was compiled with, which basically makes all obfuscators useless going by your logic.

So what exactly is your point?

**Comment by 0sir1ss** [comment]
Nuitka converts python into C code and optimises it by changing the code structure, which is then compiled into an exe.

Reversing an exe back to C is quite hard and usually results in code that is incomplete and not very readable.

Also since it converts python to C good luck with getting the original python source code.

**Comment by 6nz** [comment]
> Nuitka converts python into C code and optimises it by changing the code structure, which is then compiled into an exe.
> 
> Reversing an exe back to C is quite hard and usually results in code that is incomplete and not very readable.
> 
> Also since it converts python to C good luck with getting the original python source code.

Lol I know 2 C++ experts and they decompiled Cpython many times

**Comment by 6nz** [comment]
Ik u wont get the Python source but u will still get the C python source which is still useful if u know c
